title: smart-classroom
hero_image: images/banner.png
description: smart-classroom description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-09"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
